Config.Catalog.car_underclass = {
    {
        titel = "Motorcycles",
        vehicles = {
            {model = "sanctus", price = 10, titel = nil},
            {model = "oppressor", price = 20, titel = nil},
            {model = "double", price = 30, titel = nil},
            {model = "bati", price = 30, titel = nil},
            {model = "hakuchou2", price = 30, titel = nil},
            {model = "rrocket", price = 30, titel = nil},
            {model = "enduro", price = 30, titel = nil},
            {model = "daemon2", price = 30, titel = nil},
            {model = "diablous", price = 30, titel = nil},
            {model = "akuma", price = 30, titel = nil},
            {model = "ratbike", price = 30, titel = nil},
            {model = "carbonrs", price = 30, titel = nil},
            {model = "faggio3", price = 30, titel = nil},
            {model = "zombieb", price = 30, titel = nil},
            {model = "lectro", price = 30, titel = nil},
            {model = "hakuchou", price = 30, titel = nil},
            {model = "diablous2", price = 30, titel = nil},
            {model = "vindicator", price = 30, titel = nil},
            {model = "bagger", price = 30, titel = nil},
            {model = "nemesis", price = 30, titel = nil},
            {model = "sovereign", price = 30, titel = nil},
            {model = "faggio2", price = 30, titel = nil},
            {model = "defiler", price = 30, titel = nil},
            {model = "nightblade", price = 30, titel = nil},
            {model = "shotaro", price = 30, titel = nil},
            {model = "ruffian", price = 30, titel = nil},
            {model = "gargoyle", price = 30, titel = nil},
            {model = "avarus", price = 30, titel = nil},
            {model = "pcj", price = 30, titel = nil},
            {model = "cliffhanger", price = 30, titel = nil},
            {model = "vader", price = 30, titel = nil},
            {model = "wolfsbane", price = 30, titel = nil},
            {model = "fcr", price = 30, titel = nil},
            {model = "faggio", price = 30, titel = nil},
            --{model = "oppressor2", price = 30, titel = nil}, -- Admin Fahrzeug
            {model = "bati2", price = 30, titel = nil},
            {model = "fcr2", price = 30, titel = nil},
            {model = "vortex", price = 30, titel = nil},
            {model = "bf400", price = 30, titel = nil},
            {model = "chimera", price = 30, titel = nil},
            {model = "daemon", price = 30, titel = nil},
            {model = "zombiea", price = 30, titel = nil},
            {model = "sanchez2", price = 30, titel = nil},
            {model = "innovation", price = 30, titel = nil},
            {model = "manchez", price = 30, titel = nil},
            {model = "esskey", price = 30, titel = nil},
            {model = "thrust", price = 30, titel = nil},
            {model = "hexer", price = 30, titel = nil},
            {model = "deathbike2", price = 30, titel = nil},
            {model = "deathbike", price = 30, titel = nil},
            {model = "deathbike3", price = 30, titel = nil},
            {model = "sanchez", price = 30, titel = nil},
            {model = "stryder", price = 30, titel = nil},
        },
    },
    {
        titel = "Compacts",
        vehicles = {
            {model = "brioso", price = 10, titel = nil},
            {model = "panto", price = 20, titel = nil},
            {model = "blista", price = 30, titel = nil},
            {model = "prairie", price = 30, titel = nil},
            {model = "rhapsody", price = 30, titel = nil},
            {model = "issi2", price = 30, titel = nil},
            --{model = "dilettante2", price = 30, titel = nil}, -- company car
            {model = "dilettante", price = 30, titel = nil},
            {model = "issi4", price = 30, titel = nil},
            {model = "issi6", price = 30, titel = nil},
            {model = "issi3", price = 30, titel = nil},
            {model = "issi5", price = 30, titel = nil},
            {model = "asbo", price = 30, titel = nil},
            {model = "kanjo", price = 30, titel = nil},
            {model = "club", price = 30, titel = nil},
        },
    },

    {
        titel = "Coupes",
        vehicles = {
            {model = "sentinel", price = 10, titel = nil},
            {model = "cogcabrio", price = 20, titel = nil},
            {model = "zion2", price = 30, titel = nil},
            {model = "windsor", price = 30, titel = nil},
            {model = "felon2", price = 30, titel = nil},
            {model = "jackal", price = 30, titel = nil},
            {model = "oracle2", price = 30, titel = nil},
            {model = "windsor2", price = 30, titel = nil},
            {model = "exemplar", price = 30, titel = nil},
            {model = "felon", price = 30, titel = nil},
            {model = "zion", price = 30, titel = nil},
            {model = "f620", price = 30, titel = nil},
            {model = "sentinel2", price = 30, titel = nil},
            {model = "oracle", price = 30, titel = nil},
        },
    },

    {
        titel = "Muscle Cars",
        vehicles = {
            {model = "yosemite", price = 10, titel = nil},
            {model = "dukes2", price = 20, titel = nil},
            {model = "vamos", price = 30, titel = nil},
            {model = "dominator2", price = 30, titel = nil},
            {model = "peyote2", price = 30, titel = nil},
            {model = "vigero", price = 30, titel = nil},
            {model = "sabregt2", price = 30, titel = nil},
            {model = "ruiner3", price = 30, titel = nil},
            {model = "virgo2", price = 30, titel = nil},
            {model = "tulip", price = 30, titel = nil},
            {model = "faction", price = 30, titel = nil},
            {model = "impaler", price = 30, titel = nil},
            {model = "dominator3", price = 30, titel = nil},
            {model = "sabregt", price = 30, titel = nil},
            {model = "gauntlet2", price = 30, titel = nil},
            {model = "stalion2", price = 30, titel = nil},
            {model = "phoenix", price = 30, titel = nil},
            {model = "stalion", price = 30, titel = nil},
            {model = "blade", price = 30, titel = nil},
            {model = "lurcher", price = 30, titel = nil},
            {model = "picador", price = 30, titel = nil},
            {model = "chino2", price = 30, titel = nil},
            {model = "moonbeam2", price = 30, titel = nil},
            {model = "faction2", price = 30, titel = nil},
            {model = "tampa", price = 30, titel = nil},
            {model = "voodoo", price = 30, titel = nil},
            {model = "coquette3", price = 30, titel = nil},
            {model = "ratloader2", price = 30, titel = nil},
            {model = "dukes", price = 30, titel = nil},
            {model = "buccaneer", price = 30, titel = nil},
            {model = "chino", price = 30, titel = nil},
            {model = "moonbeam", price = 30, titel = nil},
            {model = "nightshade", price = 30, titel = nil},
            {model = "slamvan", price = 30, titel = nil},
            {model = "tampa3", price = 30, titel = nil},
            {model = "virgo3", price = 30, titel = nil},
            {model = "slamvan2", price = 30, titel = nil},
            {model = "ruiner", price = 30, titel = nil},
            {model = "voodoo2", price = 30, titel = nil},
            {model = "gauntlet", price = 30, titel = nil},
            {model = "dominator", price = 30, titel = nil},
            {model = "gauntlet4", price = 30, titel = nil},
            {model = "buccaneer2", price = 30, titel = nil},
            {model = "ratloader", price = 30, titel = nil},
            {model = "hotknife", price = 30, titel = nil},
            {model = "hermes", price = 30, titel = nil},
            {model = "slamvan3", price = 30, titel = nil},
            {model = "gauntlet3", price = 30, titel = nil},
            {model = "ruiner2", price = 30, titel = nil},
            {model = "virgo", price = 30, titel = nil},
            {model = "faction3", price = 30, titel = nil},
            {model = "imperator", price = 30, titel = nil},
            {model = "impaler2", price = 30, titel = nil},
            {model = "slamvan4", price = 30, titel = nil},
            {model = "slamvan5", price = 30, titel = nil},
            {model = "ellie", price = 30, titel = nil},
            {model = "imperator3", price = 30, titel = nil},
            {model = "dominator5", price = 30, titel = nil},
            {model = "dominator4", price = 30, titel = nil},
            {model = "impaler4", price = 30, titel = nil},
            {model = "hustler", price = 30, titel = nil},
            {model = "dominator6", price = 30, titel = nil},
            {model = "deviant", price = 30, titel = nil},
            {model = "imperator2", price = 30, titel = nil},
            {model = "impaler3", price = 30, titel = nil},
            {model = "slamvan6", price = 30, titel = nil},
            {model = "clique", price = 30, titel = nil},
            {model = "yosemite2", price = 30, titel = nil},
            {model = "dukes3", price = 30, titel = nil},
            {model = "gauntlet5", price = 30, titel = nil},
        },
    },

    {
        titel = "Offroad Cars",
        vehicles = {
            {model = "dune2", price = 10, titel = nil},
            {model = "blazer3", price = 20, titel = nil},
            {model = "rebel", price = 30, titel = nil},
            {model = "dloader", price = 30, titel = nil},
            {model = "insurgent2", price = 30, titel = nil},
            {model = "riata", price = 30, titel = nil},
            --{model = "technical2", price = 30, titel = nil}, -- Fahrzeug mit Waffe
            --{model = "dune3", price = 30, titel = nil}, -- Fahrzeug mit Waffe
            {model = "sandking2", price = 30, titel = nil},
            --{model = "technical3", price = 30, titel = nil}, -- Fahrzeug  mit Waffe
            {model = "nightshark", price = 30, titel = nil},
            --{model = "insurgent3", price = 30, titel = nil}, -- Fahrzeug mit Waffe
            {model = "caracara2", price = 30, titel = nil},
            --{model = "insurgent", price = 30, titel = nil}, -- Fahrzeug mit Waffe
            --{model = "technical", price = 30, titel = nil}, -- Fahrzeug mit Waffe
            {model = "mesa3", price = 30, titel = nil},
            --{model = "menacer", price = 30, titel = nil}, -- Fahrzeug mit Waffe
            {model = "rancherxl2", price = 30, titel = nil},
            {model = "blazer2", price = 30, titel = nil},
            {model = "bfinject", price = 30, titel = nil},
            {model = "blazer4", price = 30, titel = nil},
            {model = "bifta", price = 30, titel = nil},
            {model = "blazer", price = 30, titel = nil},
            {model = "sandking", price = 30, titel = nil},
            {model = "dune", price = 30, titel = nil},
            {model = "hellion", price = 30, titel = nil},
            --{model = "rcbandito", price = 30, titel = nil}, -- Ferngesteuert (zu klein)
            {model = "freecrawler", price = 30, titel = nil},
            {model = "trophytruck", price = 30, titel = nil},
            {model = "marshall", price = 30, titel = nil},
            {model = "bodhi2", price = 30, titel = nil},
            {model = "blazer5", price = 30, titel = nil},
            {model = "dubsta3", price = 30, titel = nil},
            {model = "brawler", price = 30, titel = nil},
            {model = "rancherxl", price = 30, titel = nil},
            {model = "rebel2", price = 30, titel = nil},
            {model = "monster", price = 30, titel = nil},
            {model = "trophytruck2", price = 30, titel = nil},
            {model = "kalahari", price = 30, titel = nil},
            {model = "dune5", price = 30, titel = nil},
            {model = "dune4", price = 30, titel = nil},
            {model = "bruiser", price = 30, titel = nil},
            {model = "brutus", price = 30, titel = nil},
            {model = "brutus3", price = 30, titel = nil},
            {model = "bfinjection", price = 30, titel = nil},
            {model = "brutus2", price = 30, titel = nil},
            {model = "monster5", price = 30, titel = nil},
            {model = "kamacho", price = 30, titel = nil},
            {model = "monster3", price = 30, titel = nil},
            {model = "monster4", price = 30, titel = nil},
            {model = "caracara", price = 30, titel = nil},
            {model = "bruiser2", price = 30, titel = nil},
            {model = "bruiser3", price = 30, titel = nil},
            {model = "zhaba", price = 30, titel = nil},
            {model = "vargant", price = 30, titel = nil},
            {model = "outlaw", price = 30, titel = nil},
            {model = "everon", price = 30, titel = nil},
        },
    },

    {
        titel = "Sedans",
        vehicles = {
            {model = "stratum", price = 10, titel = nil},
            {model = "cog55", price = 20, titel = nil},
            {model = "regina", price = 30, titel = nil},
            {model = "tailgater", price = 30, titel = nil},
            {model = "intruder", price = 30, titel = nil},
            {model = "primo2", price = 30, titel = nil},
            {model = "premier", price = 30, titel = nil},
            {model = "asea2", price = 30, titel = nil},
            {model = "washington", price = 30, titel = nil},
            {model = "stanier", price = 30, titel = nil},
            {model = "stafford", price = 30, titel = nil},
            {model = "surge", price = 30, titel = nil},
            {model = "asterope", price = 30, titel = nil},
            {model = "fugitive", price = 30, titel = nil},
            {model = "emperor2", price = 30, titel = nil},
            {model = "asea", price = 30, titel = nil},
            {model = "superd", price = 30, titel = nil},
            --{model = "limo2", price = 30, titel = nil}, -- Fahrzeug mit Waffe
            {model = "cog552", price = 30, titel = nil},
            {model = "emperor", price = 30, titel = nil},
            {model = "schafter2", price = 30, titel = nil},
            {model = "cognoscenti2", price = 30, titel = nil},
            {model = "ingot", price = 30, titel = nil},
            {model = "cognoscenti", price = 30, titel = nil},
            {model = "warrener", price = 30, titel = nil},
            {model = "primo", price = 30, titel = nil},
            {model = "glendale", price = 30, titel = nil},
            {model = "schafter5", price = 30, titel = nil},
            {model = "stretch", price = 30, titel = nil},
            {model = "romero", price = 30, titel = nil},
            --{model = "emperor3", price = 30, titel = nil}, -- beschneites Fahrzeug
            {model = "schafter6", price = 30, titel = nil},
            {model = "glendale2", price = 30, titel = nil},
        },
    },

    {
        titel = "Super Sports",
        vehicles = {
            {model = "pfister811", price = 10, titel = nil},
            {model = "italigtb", price = 10, titel = nil},
            {model = "penetrator", price = 10, titel = nil},
            {model = "cheetah", price = 10, titel = nil},
            {model = "sultanrs", price = 10, titel = nil},
            {model = "zentorno", price = 10, titel = nil},
            {model = "prototipo", price = 10, titel = nil},
            {model = "vigilante", price = 10, titel = nil},
            {model = "tezeract", price = 10, titel = nil},
            {model = "sheava", price = 10, titel = nil},
            {model = "voltic2", price = 10, titel = nil},
            {model = "infernus", price = 10, titel = nil},
            {model = "zorrusso", price = 10, titel = nil},
            {model = "xa21", price = 10, titel = nil},
            {model = "vacca", price = 10, titel = nil},
            {model = "cyclone", price = 10, titel = nil},
            {model = "s80", price = 10, titel = nil},
            {model = "nero2", price = 10, titel = nil},
            {model = "scramjet", price = 10, titel = nil},
            {model = "sc1", price = 10, titel = nil},
            {model = "osiris", price = 10, titel = nil},
            {model = "bullet", price = 10, titel = nil},
            {model = "autarch", price = 10, titel = nil},
            {model = "visione", price = 10, titel = nil},
            {model = "nero", price = 10, titel = nil},
            {model = "voltic", price = 10, titel = nil},
            {model = "fmj", price = 10, titel = nil},
            {model = "t20", price = 10, titel = nil},
            {model = "gp1", price = 10, titel = nil},
            {model = "krieger", price = 10, titel = nil},
            {model = "emerus", price = 10, titel = nil},
            {model = "banshee2", price = 10, titel = nil},
            {model = "vagner", price = 10, titel = nil},
            {model = "entityxf", price = 10, titel = nil},
            {model = "tyrus", price = 10, titel = nil},
            {model = "tempesta", price = 10, titel = nil},
            {model = "reaper", price = 10, titel = nil},
            {model = "italigtb2", price = 10, titel = nil},
            {model = "adder", price = 10, titel = nil},
            {model = "le7b", price = 10, titel = nil},
            {model = "turismor", price = 10, titel = nil},
            {model = "thrax", price = 10, titel = nil},
            {model = "entity2", price = 10, titel = nil},
            {model = "tyrant", price = 10, titel = nil},
            {model = "taipan", price = 10, titel = nil},
            {model = "furia", price = 10, titel = nil},
            {model = "tigon", price = 10, titel = nil},
        },
    },
    
    {
        titel = "Sport vehicles",
        vehicles = {
            {model = "bestiagts", price = 10, titel = nil},
            {model = "revolter", price = 20, titel = nil},
            {model = "surano", price = 30, titel = nil},
            {model = "zr3803", price = 30, titel = nil},
            {model = "carbonizzare", price = 30, titel = nil},
            {model = "schlagen", price = 30, titel = nil},
            {model = "hotring", price = 30, titel = nil},
            {model = "tropos", price = 30, titel = nil},
            {model = "infernus2", price = 30, titel = nil}, --DOUBLE
            {model = "rapidgt2", price = 30, titel = nil},
            {model = "raptor", price = 30, titel = nil},
            {model = "lynx", price = 30, titel = nil},
            {model = "sultan", price = 30, titel = nil},
            {model = "rapidgt", price = 30, titel = nil},
            {model = "schwarzer", price = 30, titel = nil},
            {model = "ninef", price = 30, titel = nil},
            {model = "massacro2", price = 30, titel = nil},
            {model = "massacro", price = 30, titel = nil},
            {model = "tampa2", price = 30, titel = nil},
            {model = "futo", price = 30, titel = nil},
            {model = "comet4", price = 30, titel = nil},
            {model = "deveste", price = 30, titel = nil},
            {model = "jester", price = 30, titel = nil},
            {model = "paragon2", price = 30, titel = nil},
            {model = "streiter", price = 30, titel = nil},
            {model = "ruston", price = 30, titel = nil},
            {model = "coquette", price = 30, titel = nil},
            {model = "zr3802", price = 30, titel = nil},
            {model = "sentinel3", price = 30, titel = nil},
            {model = "furoregt", price = 30, titel = nil},
            {model = "seven70", price = 30, titel = nil},
            {model = "dynasty", price = 30, titel = nil}, --DOUBLE
            {model = "omnis", price = 30, titel = nil},
            {model = "elegy2", price = 30, titel = nil},
            {model = "banshee", price = 30, titel = nil},
            {model = "buffalo3", price = 30, titel = nil},
            {model = "comet3", price = 30, titel = nil},
            {model = "neon", price = 30, titel = nil},
            {model = "kuruma2", price = 30, titel = nil},
            {model = "jugular", price = 30, titel = nil},
            {model = "italigto", price = 30, titel = nil},
            {model = "alpha", price = 30, titel = nil},
            {model = "fusilade", price = 30, titel = nil},
            {model = "verlierer2", price = 30, titel = nil},
            {model = "neo", price = 30, titel = nil},
            {model = "pariah", price = 30, titel = nil},
            {model = "raiden", price = 30, titel = nil},
            {model = "specter2", price = 30, titel = nil},
            {model = "schafter4", price = 30, titel = nil},
            {model = "schafter3", price = 30, titel = nil},
            {model = "elegy", price = 30, titel = nil},
            {model = "drafter", price = 30, titel = nil},
            {model = "blista3", price = 30, titel = nil},
            {model = "penumbra", price = 30, titel = nil},
            {model = "paragon", price = 30, titel = nil},
            {model = "specter", price = 30, titel = nil},
            {model = "locust", price = 30, titel = nil},
            {model = "blista2", price = 30, titel = nil},
            {model = "zr380", price = 30, titel = nil},
            {model = "buffalo", price = 30, titel = nil},
            {model = "comet2", price = 30, titel = nil},
            {model = "feltzer2", price = 30, titel = nil},
            {model = "khamelion", price = 30, titel = nil},
            {model = "ninef2", price = 30, titel = nil},
            {model = "issi7", price = 30, titel = nil},
            {model = "kuruma", price = 30, titel = nil},
            {model = "jester2", price = 30, titel = nil},
            {model = "buffalo2", price = 30, titel = nil},
            {model = "gb200", price = 30, titel = nil},
            {model = "f", price = 30, titel = nil},
            {model = "flashgt", price = 30, titel = nil},
            {model = "komoda", price = 30, titel = nil},
            {model = "imorgon", price = 30, titel = nil},
            {model = "vstr", price = 30, titel = nil},
            {model = "sultan2", price = 30, titel = nil},
            {model = "sugoi", price = 30, titel = nil},
            {model = "coquette4", price = 30, titel = nil},
            {model = "penumbra2", price = 30, titel = nil},
        },
    },

    {
        titel = "Sports classics",
        vehicles = {
            {model = "pigalle", price = 10, titel = nil},
            {model = "cheetah2", price = 20, titel = nil},
            {model = "rapidgt3", price = 30, titel = nil},
            {model = "infernus2", price = 30, titel = nil}, --DOUBLE
            {model = "casco", price = 30, titel = nil},
            {model = "stingergt", price = 30, titel = nil},
            {model = "btype3", price = 30, titel = nil},
            {model = "savestra", price = 30, titel = nil},
            {model = "viseris", price = 30, titel = nil},
            {model = "mamba", price = 30, titel = nil},
            {model = "btype", price = 30, titel = nil},
            {model = "gt500", price = 30, titel = nil},
            {model = "tornado5", price = 30, titel = nil},
            {model = "dynasty", price = 30, titel = nil}, --DOUBLE
            {model = "btype2", price = 30, titel = nil},
            {model = "ztype", price = 30, titel = nil},
            {model = "peyote", price = 30, titel = nil},
            {model = "manana", price = 30, titel = nil},
            {model = "cheburek", price = 30, titel = nil},
            {model = "tornado2", price = 30, titel = nil},
            {model = "zion3", price = 30, titel = nil},
            {model = "monroe", price = 30, titel = nil},
            {model = "stinger", price = 30, titel = nil},
            {model = "tornado4", price = 30, titel = nil},
            {model = "tornado", price = 30, titel = nil},
            {model = "ardent", price = 30, titel = nil},
            {model = "coquette2", price = 30, titel = nil},
            {model = "jb700", price = 30, titel = nil},
            {model = "tornado6", price = 30, titel = nil}, 
            {model = "feltzer3", price = 30, titel = nil},
            {model = "turismo2", price = 30, titel = nil},
            {model = "tornado3", price = 30, titel = nil},
            {model = "torero", price = 30, titel = nil},
            {model = "swinger", price = 30, titel = nil},
            {model = "deluxo", price = 30, titel = nil},
            {model = "retinue", price = 30, titel = nil},
            {model = "stromberg", price = 30, titel = nil},
            {model = "nebula", price = 30, titel = nil},
            {model = "z190", price = 30, titel = nil},
            {model = "jester3", price = 30, titel = nil},
            {model = "michelli", price = 30, titel = nil},
            {model = "fagaloa", price = 30, titel = nil},
            {model = "retinue2", price = 30, titel = nil},
            {model = "jb7002", price = 30, titel = nil},
            {model = "manana2", price = 30, titel = nil},
            {model = "peyote3", price = 30, titel = nil},
        },
    },

    {
        titel = "SUV\'s",
        vehicles = {
            {model = "landstalker", price = 10, titel = nil},
            {model = "patriot", price = 20, titel = nil},
            {model = "serrano", price = 30, titel = nil},
            {model = "seminole", price = 30, titel = nil},
            {model = "gresley", price = 30, titel = nil},
            {model = "baller2", price = 30, titel = nil},
            {model = "xls", price = 30, titel = nil},
            {model = "novak", price = 30, titel = nil},
            {model = "mesa", price = 30, titel = nil},
            {model = "baller", price = 30, titel = nil},
            {model = "cavalcade2", price = 30, titel = nil},
            {model = "dubsta2", price = 30, titel = nil},
            {model = "baller6", price = 30, titel = nil},
            {model = "patriot2", price = 30, titel = nil},
            {model = "bjxl", price = 30, titel = nil},
            {model = "xls2", price = 30, titel = nil},
            {model = "baller4", price = 30, titel = nil},
            {model = "baller3", price = 30, titel = nil},
            {model = "huntley", price = 30, titel = nil},
            {model = "fq2", price = 30, titel = nil},
            {model = "baller5", price = 30, titel = nil},
            {model = "granger", price = 30, titel = nil},
            {model = "contender", price = 30, titel = nil},
            --{model = "mesa2", price = 30, titel = nil}, -- beschneites Fahrzeug
            {model = "cavalcade", price = 30, titel = nil},
            {model = "habanero", price = 30, titel = nil},
            {model = "toros", price = 30, titel = nil},
            {model = "dubsta", price = 30, titel = nil},
            {model = "rocoto", price = 30, titel = nil},
            {model = "radi", price = 30, titel = nil},
            {model = "rebla", price = 30, titel = nil},
            {model = "landstalker2", price = 30, titel = nil},
            {model = "seminole2", price = 30, titel = nil},
        },
    },

    {
        titel = "Vans",
        vehicles = {
            {model = "rumpo2", price = 10, titel = nil},
            {model = "burrito4", price = 20, titel = nil},
            {model = "bobcatxl", price = 30, titel = nil},
            {model = "pony", price = 30, titel = nil},
            {model = "boxville3", price = 30, titel = nil},
            {model = "paradise", price = 30, titel = nil},
            {model = "camper", price = 30, titel = nil},
            {model = "burrito", price = 30, titel = nil},
            {model = "gburrito", price = 30, titel = nil},
            {model = "surfer", price = 30, titel = nil},
            {model = "rumpo3", price = 30, titel = nil},
            {model = "rumpo", price = 30, titel = nil, livery = 1},
            {model = "boxville2", price = 30, titel = nil},
            --{model = "boxville5", price = 30, titel = nil}, -- Fahrzeug mit Waffe
            {model = "boxville4", price = 30, titel = nil},
            {model = "journey", price = 30, titel = nil},
            {model = "youga", price = 30, titel = nil},
            {model = "bison2", price = 30, titel = nil},
            {model = "bison3", price = 30, titel = nil},
            {model = "burrito3", price = 30, titel = nil},
            {model = "minivan2", price = 30, titel = nil},
            {model = "bison", price = 30, titel = nil},
            {model = "speedo2", price = 30, titel = nil},
            {model = "youga2", price = 30, titel = nil},
            {model = "speedo", price = 30, titel = nil},
            {model = "boxville", price = 30, titel = nil},
            {model = "pony2", price = 30, titel = nil},
            {model = "minivan", price = 30, titel = nil},
            {model = "burrito5", price = 30, titel = nil},
            {model = "gburrito2", price = 30, titel = nil},
            {model = "taco", price = 30, titel = nil},
            {model = "surfer2", price = 30, titel = nil},
            {model = "burrito2", price = 30, titel = nil},
            {model = "speedo4", price = 30, titel = nil},
            {model = "youga3", price = 30, titel = nil},
        },
    },

    {
        titel = "Limited-edition",
        vehicles = {
            --{model = "sanctus", price = 10, titel = nil},
        },
    },

    {
        titel = "VIP\'s",
        vehicles = {
            {model = "formula2", price = 10, titel = nil},
            {model = "formula", price = 10, titel = nil},
            {model = "openwheel1", price = 10, titel = nil},
            {model = "openwheel2", price = 10, titel = nil},
        },
    },
}
